name = "RateConversion"
uuid = "cb606a77-1f6d-4680-a3b9-a4d0e7bc5159"
authors = ["Roy <rwang013@uottawa.ca> and contributors"]
version = "0.1.0"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
julia = "1"

[targets]
test = ["Test"]
